name: Atualizar JSONs

on:
  workflow_dispatch:

jobs:

  converter:

    runs-on: ubuntu-latest

    steps:

      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Criar pasta entrada
        run: mkdir -p entrada

      - name: Baixar CSV do Google Drive
        run: |
          curl -L "https://drive.google.com/uc?export=download&id=1zYfqIrgmebYYHVog4k_xCq5aABMuLvm9" -o entrada/base.csv

      - name: Executar conversão
        run: node converter.js

      - name: Commit automático
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          rm -f entrada/base.csv

git add dados indexes.json

git commit -m "Atualização automática dos JSONs" || echo "Sem alterações"

git push

          git commit -m "Atualização automática dos JSONs" || echo "Sem alterações"

          git push
